// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqz2vMQykvSWZMJI228b3vgDGxypTszvQ',
    appId: '1:162884669350:web:d072fc856c1fcf0cb08967',
    messagingSenderId: '162884669350',
    projectId: 'fir-flutter-auth-5d915',
    authDomain: 'fir-flutter-auth-5d915.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-5d915.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqrrr7Pi83ZuCJjGQms5SiTzhi8jHxOE',
    appId: '1:162884669350:android:61c25c9f3bfc4fb9b08967',
    messagingSenderId: '162884669350',
    projectId: 'fir-flutter-auth-5d915',
    storageBucket: 'fir-flutter-auth-5d915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh9GHImDgCY2fe5BV19EcWWIhq7NksenU',
    appId: '1:162884669350:ios:858b1295de22decab08967',
    messagingSenderId: '162884669350',
    projectId: 'fir-flutter-auth-5d915',
    storageBucket: 'fir-flutter-auth-5d915.appspot.com',
    iosClientId: '162884669350-skm36ikuhtvhng41at5fev6qtdrvuaor.apps.googleusercontent.com',
    iosBundleId: 'com.example.actividad1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh9GHImDgCY2fe5BV19EcWWIhq7NksenU',
    appId: '1:162884669350:ios:858b1295de22decab08967',
    messagingSenderId: '162884669350',
    projectId: 'fir-flutter-auth-5d915',
    storageBucket: 'fir-flutter-auth-5d915.appspot.com',
    iosClientId: '162884669350-skm36ikuhtvhng41at5fev6qtdrvuaor.apps.googleusercontent.com',
    iosBundleId: 'com.example.actividad1',
  );
}
